name: ${COMPOSE_PROJECT_NAME:-ercs-cms}

services:
  react:
    build:
      context: ../
      target: dev
    command: sh -c 'pnpm install --frozen-lockfile && pnpm run dev --host'
    volumes:
      - ../:/code
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - CI=true
      - PORT=${PORT:-3000}
      - APP_GRAPHQL_ENDPOINT=${APP_GRAPHQL_ENDPOINT:-http://web:8000/graphql/}
      - APP_GRAPHQL_CODEGEN_ENDPOINT=${APP_GRAPHQL_CODEGEN_ENDPOINT:-./backend/schema.graphql}
    env_file:
      - .env
    depends_on:
      - web
