name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

env:
  APP_GRAPHQL_CODEGEN_ENDPOINT: "./backend/schema.graphql"
  APP_GRAPHQL_ENDPOINT: "http://web:8000/graphql/"
  APP_TITLE: "ERCS CMS"
  APP_ENVIRONMENT: "development"
  GITHUB_WORKFLOW: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      PIPELINE_TYPE: ci
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint
  build:
    name: Build
    needs: [lint]
    runs-on: ubuntu-latest
    env:
      PIPELINE_TYPE: ci
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Type
        run: pnpm generate:type

      - name: Build
        run: pnpm build